### ISSUE TITLE
diskMount: formatAndMount failed, err: disk number out of range: "101"

### ISSUE THREAD

**Issue by axelgMS** [kubernetes/mount-utils#2]
CRI 234511173

Error from Windows node pool on Azure AKS 1.18.14.
Windows node image = AKSWindows-2019-17763.1817.210310

kubelet error says:

```
I0402 14:47:59.657678    6416 operation_generator.go:567] MountVolume.WaitForAttach succeeded for volume "pvc-1e3a8013-0797-4823-8931-cb4b568d20f4" (UniqueName: "kubernetes.io/azure-disk//subscriptions/XYZ/resourceGroups/XYZ/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-1e3a8013-0797-4823-8931-cb4b568d20f4") pod "mssql-cd44fcc5d-sh5kf" (UID: "ec1b4004-5006-47b1-87eb-0781696bf510") DevicePath "/dev/disk101"
…
E0402 14:47:59.658685    6416 mount_windows.go:222] diskMount: formatAndMount failed, err: disk number out of range: "101"

```

“formatAndMount failed” error comes from here, and is happening after the ValidateDiskNumber() defined here, which says:

```
// ValidateDiskNumber : disk number should be a number in [0, 99]
func ValidateDiskNumber(disk string) error {
      diskNum, err := strconv.Atoi(disk)
      if err != nil {
            return fmt.Errorf("wrong disk number format: %q, err:%v", disk, err)
      }

      if diskNum < 0 || diskNum > 99 {
            return fmt.Errorf("disk number out of range: %q", disk)
      }

      return nil
}
```

Not yet sure why Windows reports the disk with an ID / LUN of 101 - as there was only a few Data Disks attached to the VM when the issue occurred.

**Comment by jingxu97** [comment]
cc @ddebroy

**Comment by andyzhangx** [comment]
@axelgMS I will port code change(https://github.com/kubernetes/kubernetes/pull/105673) to this repo. 
off the topic:
Just curious, why there is 101 disk num in Azure Windows node, as I could remember, Azure VM could only support 64 data disks at most.
